### ISSUE TITLE
KernelSU Support

### ISSUE THREAD

**Issue by raphaelbahat** [yzyhk904/audio-samplerate-changer#4]
Could you please add support for KernelSU?

**Comment by yzyhk904** [comment]
KernelSU as well as Magisk v28.0 (except Magisk v27.0 and former) has an issue for correct module updating generally because of lacking mirrors (i.e., original files to modify when updating modules).

If you want install this module anyway, use my another module [Compatible Magisk-mirroring](https://github.com/Magisk-Modules-Alt-Repo/compatible-magisk-mirroring).
